---
name: "ae-receipts"
author: "Jonathan Strickland"

dependencies:
  - base
  - text
  - bytestring
  - megaparsec
  - parser-combinators

library:
  source-dirs:
    - src

default-extensions:
  - OverloadedStrings
  - RecordWildCards
